project_name: wgmitmgui

release:
  prerelease: auto

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '7'
    ignore:
      - goos: darwin
        goarch: arm
        goarm: 7
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
- format: binary

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Merge pull request'
